export const VERIFIED_CLIENTS = [
  {
    id: 'talk-to-my-lawyer',
    person: 'Ravivo Kaufman',
    role: 'Owner',
    company: 'Talk to My Lawyer',
    website: 'https://talktomylawyer.com',
    websiteLabel: 'talktomylawyer.com',
    recordLabel: 'Original client record',
    summary: 'Ravivo Kaufman, owner of Talk to My Lawyer, was identified directly as an original Crystal Web Solution client.',
    palette: ['#59f3ff', '#3c6cff'],
  },
  {
    id: 'tucker-trips',
    person: 'Kristin Stein',
    role: null,
    company: 'Tucker Trips',
    website: 'https://tuckertrips.com',
    websiteLabel: 'tuckertrips.com',
    recordLabel: 'Original client record',
    summary: 'Kristin Stein of Tucker Trips was identified directly as an original Crystal Web Solution client.',
    palette: ['#c084fc', '#ff8dd1'],
  },
  {
    id: 'zues-towing',
    person: 'Porsha Patterson',
    role: null,
    company: 'Zues Towing',
    website: null,
    websiteLabel: null,
    reviewId: 'porsha-patterson',
    recordLabel: 'Original client • supplied 5/5 review',
    summary: 'Porsha Patterson of Zues Towing gave a supplied 5/5 review citing professionalism, customer service, and plans for future work.',
    palette: ['#b9ff4a', '#ff8c73'],
  },
];
